#!/bin/bash

NAME="HW3"  #Django application name
DIR=/home/ubuntu/django_deploy_app/test_django_app   #Directory where project is located
USER=root   #User to run this script as
GROUP=root  #Group to run this script as
WORKERS=3     #Number of workers that Gunicorn should spawn
SOCKFILE=unix:/home/ubuntu/django_deploy_app/gunicorn.sock   #This socket file will communicate with Nginx 
DJANGO_SETTINGS_MODULE=HW3.settings   #Which Django setting file should use
DJANGO_WSGI_MODULE=HW3.wsgi           #Which WSGI file should use
LOG_LEVEL=debug
cd $DIR
source /home/ubuntu/django_deploy_app/venv/bin/activate  #Activate the virtual environment
export DJANGO_SETTINGS_MODULE=$DJANGO_SETTINGS_MODULE
export PYTHONPATH=$DIR:$PYTHONPATH


#Command to run the progam under supervisor
exec /home/ubuntu/django_deploy_app/venv/bin/gunicorn ${DJANGO_WSGI_MODULE}:application \
--name $NAME \
--workers $WORKERS \
--user=$USER \
--group=$GROUP \
--bind=$SOCKFILE \
--log-level=$LOG_LEVEL \
--log-file=-
