name: Deploy

on:
  push:
    branches:
    - master
jobs:
  build:
  
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.6]
    steps:
      - uses: actions/checkout@v3
      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@master
        with:
          host: 139.59,129.115
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: 22
          script: |
            cd back_hw3
            source ./venv/bin/activate
            git pull
            python manage.py migrate
            python manage.py collectstatic --noinput
            supervisorctl restart all
